version: '3.8'

services:
  app:
    image: registry.pitechplus.com/flavia.andron/symfony-6-framework-hands-on-2023
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www

  server:
    image: nginx:1.21-alpine
    env_file: .env
    volumes:
      - ./src:/var/www
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "8000:80"
    networks:
      default:
        aliases:
          - ${APP_HOST}
    depends_on:
      - app

  mysql:
    image: mariadb:10.8.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - '/mariadb/:/var/lib/mysql'
    ports:
      - '3306:3306'

  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'

  mailer:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"

