version: '3.8'

services:
  app:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ../src:/var/www
    working_dir: /var/www/

  server:
    image: nginx:1.21
    env_file: .env
    volumes:
      - /nginx:/usr/share/nginx/html/
    ports:
      - "8000:80"
    networks:
      default:
        aliases:
          - ${APP_HOST}
    depends_on:
      - app

  mysql:
    image: mariadb:10.8.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - '/mariadb/:/var/lib/mysql'

  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'

  mailer:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"

